### PR TITLE
openstack: deprecate some openstack services

### PR DESCRIPTION
**Pull request by berendt**
Signed-off-by: Christian Berendt <berendt@osism.tech>

### CODE REVIEW

**Comment by berendt** [comment]
Has to be discusses with SCS first.

**Comment by berendt** [comment]
Should we also deprecate Horizon in favour of Skyline? Skyline 1.0.0 is available and will be integrated the next months.

**Comment by osfrickler** [comment]
AFAICT Skyline does not yet have feature parity with Horizon, e.g. support for Designate is missing. So I think that it is too early to deprecate Horizon.

**Comment by cedegi** [comment]
Quoted from https://www.openstack.org/software/zed/

"Skyline is considered by the OpenStack Technical Committee to be in an "emerging technology state,” not yet ready for production."

I really look forward to skyline. Meanwhile on our side we experienced quite a lot of bugs and missed some features. Anyway, that's nothing where horizon is better at ;)

**Pull request merged**
