### PR TITLE
Add a script to prepare a git diff log on stable branches

### PR DESCRIPTION
**Pull request by berendt**

### CODE REVIEW

**Comment by berendt** [comment]
@fkr What do you think about https://github.com/osism/release/blob/0cf03bffd8647791172192f510da39698ccf8827/src/README.md? This table will be added to the 5.2.0 release notes as an appendix.

**Comment by fkr** [comment]
@berendt very good idea. I did wonder, wether it would be nice to sort it via component and within that order then by date - that way it is even easier to spot changes for certain components.

**Comment by berendt** [comment]
@fkr What do you think about https://github.com/osism/release/blob/cd33cafc5d5f0c76ff6461c408c173c15de69e5a/src/README.md?

**Comment by fkr** [comment]
awesome 🥳

**Pull request merged**
